apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipfs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ipfs
  template:
    metadata:
      labels:
        app: ipfs
    spec:
      containers:
      - name: ipfs
        image: 339713100066.dkr.ecr.us-east-1.amazonaws.com/ipfs:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "your-rds-endpoint.amazonaws.com"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: rds-db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rds-db-credentials
              key: password
        - name: DB_NAME
          value: "your-database-name"        

---

apiVersion: v1
kind: Service
metadata:
  name: ipfs
spec:
  type: LoadBalancer
  selector:
    app: ipfs
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080


---
apiVersion: v1
kind: Secret
metadata:
  name: rds-db-credentials
type: Opaque
data:
  username: aXBmc191c2Vy
  password: aXBmc19wYXNz     