name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli
        sudo apt-get install -y kubectl
        curl -o aws-iam-authenticator https://amazon-eks.s3-us-east-2.amazonaws.com/1.16.8/2020-07-23/bin/linux/amd64/aws-iam-authenticator
        chmod +x ./aws-iam-authenticator
        sudo mv ./aws-iam-authenticator /usr/local/bin/

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Log in to Amazon ECR
      id: ecr-login
      uses: aws-actions/amazon-ecr-login@v1
      with:
        region: ${{ secrets.AWS_REGION }}

    - name: Build, tag, and push Docker image to ECR
      env:
        ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME }}
        IMAGE_TAG: latest
      run: |
        echo "Building 2 Docker image ipfs-metadata:${IMAGE_TAG}"
        docker build -t ipfs-metadata:${IMAGE_TAG} -f server/Dockerfile server/
        echo "Tagging Docker image"
        docker tag ipfs-metadata:latest 339713100066.dkr.ecr.us-east-1.amazonaws.com/ipfs-metadata:latest
        docker push 339713100066.dkr.ecr.us-east-1.amazonaws.com/ipfs-metadata:latest

     