name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List files (for debugging)
      run: ls -R

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli
        sudo apt-get install -y kubectl
        curl -o aws-iam-authenticator https://amazon-eks.s3-us-east-2.amazonaws.com/1.16.8/2020-07-23/bin/linux/amd64/aws-iam-authenticator
        chmod +x ./aws-iam-authenticator
        sudo mv ./aws-iam-authenticator /usr/local/bin/

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Create ECR repository if it doesn't exist
      run: |
        aws ecr describe-repositories --repository-names ${{ secrets.ECR_REPOSITORY_NAME }} || \
        aws ecr create-repository --repository-name ${{ secrets.ECR_REPOSITORY_NAME }}

    - name: Log in to Amazon ECR
      id: ecr-login
      uses: aws-actions/amazon-ecr-login@v1
      with:
        region: ${{ secrets.AWS_REGION }}

    - name: Build, tag, and push Docker image to ECR
      env:
        ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME }}
        IMAGE_TAG: latest
      run: |
        echo "Building Docker image ipfs:${IMAGE_TAG}"
        docker build -t ipfs:${IMAGE_TAG} -f Dockerfile .
        echo "Tagging Docker image"
        docker tag ipfs:latest ${{ steps.ecr-login.outputs.registry }}/${{ secrets.ECR_REPOSITORY_NAME }}:latest
        docker push ${{ steps.ecr-login.outputs.registry }}/${{ secrets.ECR_REPOSITORY_NAME }}:latest

    - name: Update kube config
      run: aws eks update-kubeconfig --name ipfs-cluster      

    - name: Deploy to Kubernetes
      env:
        ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME }}
        IMAGE_TAG: latest
      run: |
        echo "Updating 2 Kubernetes deployment with image $ECR_REGISTRY/$ECR_REPOSITORY:${IMAGE_TAG}"
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ steps.ecr-login.outputs.registry }}
        kubectl set image deployment/ipfs ipfs=${{ steps.ecr-login.outputs.registry }}/ipfs:latest
        kubectl rollout restart deployment ipfs        
